on:
  push:
    branches:
      - master
  pull_request:

jobs:
  run_fate:
    strategy:
      fail-fast: false
      matrix:
        runner: [linux-amd64,linux-aarch64]
    runs-on: ${{ matrix.runner }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Configure
        run: ./configure
      - name: Build
        run: make -j$(nproc)
      - name: Restore Cached Fate-Suite
        uses: actions/cache/restore@v4
        with:
          path: fate-suite
          key: fate-suite
          restore-keys: |
            fate-suite-
      - name: Sync Fate-Suite
        id: fate
        run: |
          make fate-rsync SAMPLES=$PWD/fate-suite
          echo "hash=$(find fate-suite -type f | sha256sum | cut -d' ' -f1)" >> $GITHUB_OUTPUT
      - name: Cache Fate-Suite
        uses: actions/cache/save@v4
        with:
          path: fate-suite
          key: fate-suite-${{ steps.fate.outputs.hash }}
      - name: Add extra samples
        run: |
          cd $PWD/fate-suite
          curl 'https://www.dropbox.com/scl/fo/xrtrna2rxr1j354hrtymq/AGwemlxHYecBLNmQ8Fsy--4?rlkey=lzilr4m9w4gfdqygoe172vvy8&dl=1' -L -o extra-samples.zip
          unzip extra-samples.zip || true
          rm -f extra-samples.zip
      - name: Run Fate
        run: make fate SAMPLES=$PWD/fate-suite -j$(nproc)
