on:
  push:
    branches:
      - master
  pull_requests:

runs:
  using: 'docker'
  image: 'image/Dockerfile'

jobs:
  run_fate:
    runs-on: linux-amd64
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Configure
        run: ./configure
      - name: Build
        run: make -j$(nproc)
      - name: Restore Cached Fate-Suite
        uses: actions/cache/restore@v4
        with:
          path: fate-suite
          key: fate-suite
          restore-keys: |
            fate-suite-
      - name: Sync Fate-Suite
        id: fate
        run: |
          make fate-rsync SAMPLES=$PWD/fate-suite
          echo "hash=$(find fate-suite -type f | sha256sum | cut -d' ' -f1)" >> $GITHUB_OUTPUT
      - name: Cache Fate-Suite
        uses: actions/cache/save@v4
        with:
          path: fate-suite
          key: fate-suite-${{ steps.fate.outputs.hash }}
      - name: Run Fate
        run: make fate SAMPLES=$PWD/fate-suite -j$(nproc)
